name: setup-kubeconfig
on: workflow_dispatch
jobs:
  setup:
    runs-on: self-hosted
    env:
      KCFG: ${{ github.workspace }}/kubernetes-kubeconfig
    steps:
      - uses: actions/checkout@v4

      - name: Write kubeconfig
        shell: bash
        run: |
          [ -f "$KCFG" ] && rm "$KCFG"

          kubectl config --kubeconfig="$KCFG" set-cluster kubernetes \
            --server="${{ secrets.KUBE_APISERVER }}" \
            --certificate-authority-data="${{ secrets.KUBE_CA }}"

          kubectl config --kubeconfig="$KCFG" set-credentials github-actions \
            --token="${{ secrets.KUBE_TOKEN }}"

          kubectl config --kubeconfig="$KCFG" set-context github-actions \
            --cluster=kubernetes --user=github-actions --namespace=demo

          kubectl config --kubeconfig="$KCFG" use-context github-actions
          echo "KUBECONFIG=$KCFG" >> "$GITHUB_ENV"
